#!/usr/bin/env sh
# SPDX-FileCopyrightText: 2024 Robin Vobruba <hoijui.quaero@gmail.com>
# SPDX-License-Identifier: Unlicense

set -eu

script_path="$(readlink -f "$0")"
script_dir="$(dirname "$script_path")"
script_name="$(basename "$script_path")"

src_dir="$script_dir/.."
build_dir="$script_dir/../public"
js_file="htmlpreview.js"
js_minified="$build_dir/$js_file"
index_combined="$build_dir/index_combined.html"
index_combined_minified="$build_dir/index_combined_minified.html"
index_final="$build_dir/index.html"

print_help() {

	echo "$script_name - Creates the release version of this tool."
	echo "This minifies the JavaScript file, inserts it into the HTML (in-line),"
	echo "and then also minifies the HTML and CSS,"
	echo "leaving the final result at:"
	echo "$index_final"
}

# read command-line args
i=1
while [ "$i" -lt "$#" ]
do
	arg="$(eval "echo \$$i")"

	case "$arg" in
		-h|--help)
			shift "$i"
			print_help
			exit 0
			;;
		*) # non-/unknown option
			i=$((i + 1))
			;;
	esac
done

mkdir -p "$build_dir"

# Minify the JavaScript
npx --no-install \
	uglify-js \
		--compress \
		--output "$js_minified" \
		-- \
		"$src_dir/$js_file"

# Inserts the minified JavaScript into a copy of index.html,
# thus combininig everything into a single file.
awk '
	NR==FNR {
		a[n++] = $0
		next
	}
	/<script src="'"$js_file"'"><\/script>/ {
		print "<script>"
		for (i = 0; i < n; ++i) {
			print a[i]
		}
		print "</script>"
		next
	}
	1' \
	"$js_minified" \
	"$src_dir/index.html" \
	> "$index_combined"

# Minifies the HTML and CSS in the above combined file.
# NOTE While this tool (`@minify-html/node`) is also able to
#      minify contained JavaScript, it introduces bugs,
#      which is why we minify it before combining with
#      `uglify-js` above.
npx --no-install \
	@minify-html/node \
		--output "$index_combined_minified" \
		--minify-css \
		--keep-closing-tags \
		--keep-spaces-between-attributes \
		--do-not-minify-doctype \
		"$index_combined"

# Marks the combined & minified version as the one to be used.
rm -f "$index_final"
ln -s "$index_combined_minified" "$index_final"
